### ISSUE TITLE
Missing medium source flie

### ISSUE THREAD

**Issue by jgornowich** [mp3monster/LogGenerator#4]
The book references `./TestData/medium-source.txt` several times and there is no such file in this repo.  Is this a missing file or a typo in the book?

**Comment by mp3monster** [comment]
nice spot.  It was in the manning download. But seems to have been omitted from this repo.  Will upload shortly.

Apologies

**Comment by mp3monster** [comment]
omitted files now included

**Comment by jgornowich** [comment]
Thanks, your right. I didn't actually download the source from manning initially but instead just pulled the two github repos.  

One more quick observation is that the folder here is called `testData` and the one in the manning download and in the book text is `TestData`.

**Comment by mp3monster** [comment]
Thanks for highlighting - have also corrected folder name. Also tweaked the documentation (readme). As the repo doesn't contain the tutorial config solutions etc. They remain with the book
