### ISSUE TITLE
Examples in the book are not working

### ISSUE THREAD

**Issue by LamboYu** [mp3monster/LogGenerator#5]
I can't generate the logs per instructions from the book: Logging in Action: With Fluentd, Kubernetes and more, I guess there should be a commitment up to which the examples in the book are working, can you please give the commitment id?

**Comment by mp3monster** [comment]
The configurations should work.  If you can share which case you've found not to be working would be helpful - so I can look more closely.  Have you downloaded from the release or from the latest?

**Comment by abbasimo** [comment]
PS C:\Users\Mohamad\Desktop\code\LogGenerator> groovy .\LogSimulator.groovy ..\LoggingInActionWithFluentd\Chapter2\SimulatorConfig\tool.properties
Starting ...
Going to use ..\LoggingInActionWithFluentd\Chapter2\SimulatorConfig\tool.properties
handling properties file - ..\LoggingInActionWithFluentd\Chapter2\SimulatorConfig\tool.properties
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
createLogEntry Line>0< >2< false
createLogEntry Line>1< >2< false
logToString iterCount=>1< counter=>1< output=>{"message": "%m"}< dtgFormat=>HH:mm:ss< log=>offset=100|INFO||com.demo|hello<-
logToString - returns:{"message": "hello"}
^CTerminate batch job (Y/N)? y

**Comment by mp3monster** [comment]
> PS C:\Users\Mohamad\Desktop\code\LogGenerator> groovy .\LogSimulator.groovy ..\LoggingInActionWithFluentd\Chapter2\SimulatorConfig\tool.properties Starting ... Going to use ..\LoggingInActionWithFluentd\Chapter2\SimulatorConfig\tool.properties handling properties file - ..\LoggingInActionWithFluentd\Chapter2\SimulatorConfig\tool.properties createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false createLogEntry Line>0< >2< false createLogEntry Line>1< >2< false logToString iterCount=>1< counter=>1< output=>{"message": "%m"}< dtgFormat=>HH:mm:ss< log=>offset=100|INFO||com.demo|hello<- logToString - returns:{"message": "hello"} ^CTerminate batch job (Y/N)? y

Looking at the configuration - it looks like the problem is that the log simulator is being run from the wrong folder, as a result it  isn't able to load the test data file properly. as it uses a relative path try modifying the Chapter2\SimulatorConfig\tool.properties file so that the path to the TestData folder is absolute rather than relative
